version: "3.9"
services:
  server:
    build:
      context: server
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: .env
    environment:
      - PORT=${SERVER_PORT}
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
  client:
    build:
      context: client 
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: .env
    environment:
      - PORT=${CLIENT_PORT}
      - REACT_APP_SERVER_URL=http://localhost:${SERVER_PORT}
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}
  
